name: Bike Rental Prediction CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/test_requirements.txt
          
      - name: Model Training
        run: |
          python3 bikeshare_model/train_pipeline.py
      
      - name: Model Prediction
        run: |
            python3 bikeshare_model/predict.py

      - name: Model test
        run: |
            python3 -m pip install pytest
            pytest

  build-package-and-containerize:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    needs: train-and-test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          docker: latest

      - name: Install Dependencies
        run: |
          pip install -r requirements/test_requirements.txt

      - name: Build and Package
        run: |
          python3 -m pip install build
          python -m build

      #- name: Set up Docker
      #  uses: docker/setup-docker@v2.7.0
  
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        run: |
            COMMIT_SHA=$(git rev-parse --short=7 HEAD)
            docker build -t sumanthegdedocker/bikeshare_model_api:$COMMIT_SHA .
            docker push sumanthegdedocker/bikeshare_model_api:$COMMIT_SHA

  # dockerize:
  #   runs-on: ubuntu-latest

  #   needs: build-and-package

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with: 
  #         push: true
  #         tags: user/app:latest
        #run: |
          #COMMIT_SHA=$(git rev-parse --short=7 HEAD)
          #docker build -t durgeshshisode1988/bikeshare_model_api:$COMMIT_SHA .

  # push-to-dockerhub:
  #   runs-on: ubuntu-latest

  #   needs: dockerize

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Set up Docker
  #       uses: docker/setup-docker@v2

  #     - name: Log in to Docker Hub
  #       run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

  #     - name: Push Docker Image to Docker Hub
  #       run: |
  #         docker push your-dockerhub-username/your-image-name:$COMMIT_SHA